<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Instansi;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Schema;

class InstansiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Matikan proteksi foreign key agar bisa menghapus data yang berelasi
        Schema::disableForeignKeyConstraints();
        
        // 2. Kosongkan tabel agar data lama tidak menumpuk
        Instansi::truncate();
        
        // 3. Hidupkan kembali proteksi foreign key
        Schema::enableForeignKeyConstraints();

        // 4. Data instansi lengkap dengan Media Sosial
        $instansis = [
            [
                'nama' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu (DPMPTSP) Prov. Jawa Tengah',
                'subtitle' => 'DPMPTSP JAWA TENGAH',
                'alamat' => 'Jl. Menteri Supeno No. 6, Kota Semarang',
                'kontak' => '(024) 831-3456',
                'website' => 'https://dpmptsp.jatengprov.go.id',
                'logo' => 'instansi/DPMPTSP JATENG.png',
                'facebook' => 'https://facebook.com/dpmptsp.jateng',
                'instagram' => 'https://instagram.com/dpmptsp_jateng',
                'twitter' => 'https://twitter.com/dpmptsp_jateng',
            ],
            [
                'nama' => 'Unit Pelaksana Teknis Badan Pelindungan Pekerja Migran Indonesia (UPT BP2MI) Kota Semarang',
                'subtitle' => 'UPT B2MI KOTA SEMARANG',
                'alamat' => 'Jl. Pamularsih Raya No. 10, Kota Semarang',
                'kontak' => '(024) 760-1122',
                'website' => 'https://bp2mi.go.id',
                'logo' => 'instansi/BP2MI.png',
                'facebook' => 'https://facebook.com/bp2mi.ri',
                'instagram' => 'https://instagram.com/bp2mi_ri',
                'twitter' => 'https://twitter.com/bp2mi_ri',
            ],
            [
                'nama' => 'Unit Pengelolaan Pendapatan Daerah (UPPD) Kab. Sukoharjo',
                'subtitle' => 'UPPD SUKOHARJO',
                'alamat' => 'Jl. Jenderal Sudirman No. 199, Sukoharjo',
                'kontak' => '(0271) 593-456',
                'website' => 'https://bapenda.jatengprov.go.id',
                'logo' => 'instansi/UPPD.png',
                'facebook' => 'https://facebook.com/SamsatSukoharjo',
                'instagram' => 'https://instagram.com/samsatsukoharjo',
                'twitter' => 'https://twitter.com/samsatsukoharjo',
            ],
            [
                'nama' => 'Polres Sukoharjo',
                'subtitle' => 'POLRES SUKOHARJO',
                'alamat' => 'Jl. Ir. Soekarno No. 5, Sukoharjo',
                'kontak' => '(0271) 593-110',
                'website' => 'https://polressukoharjo.polri.go.id',
                'logo' => 'instansi/polres.jpg',
                'facebook' => 'https://facebook.com/PolresSukoharjoOfficial',
                'instagram' => 'https://instagram.com/polressukoharjo',
                'twitter' => 'https://twitter.com/res_sukoharjo',
            ],
            [
                'nama' => 'Kejaksaan Negeri Sukoharjo',
                'subtitle' => 'KEJAKSAAN SUKOHARJO',
                'alamat' => 'Jl. Jaksa Agung R. Suprapto No. 1, Sukoharjo',
                'kontak' => '(0271) 593-221',
                'website' => 'https://kejari-sukoharjo.kejaksaan.go.id',
                'logo' => 'instansi/KEJAKSAAN.png',
                'facebook' => 'https://facebook.com/kejari.sukoharjo',
                'instagram' => 'https://instagram.com/kejari.sukoharjo',
                'twitter' => 'https://twitter.com/kejarisukoharjo',
            ],
            [
                'nama' => 'Kementerian Agama Kab. Sukoharjo',
                'subtitle' => 'KEMENTERIAN AGAMA SUKOHARJO',
                'alamat' => 'Jl. Veteran No. 8, Sukoharjo',
                'kontak' => '(0271) 593-889',
                'website' => 'https://sukoharjo.kemenag.go.id',
                'logo' => 'instansi/KEMENTERIAN AGAMA.png',
                'facebook' => 'https://facebook.com/kemenag.sukoharjo',
                'instagram' => 'https://instagram.com/kemenag_sukoharjo',
                'twitter' => 'https://twitter.com/kemenag_skh',
            ],
            [
                'nama' => 'Pengadilan Negeri Sukoharjo Kelas IA',
                'subtitle' => 'PENGADILAN NEGERI SUKOHARJO',
                'alamat' => 'Jl. Jaksa Agung R. Suprapto No. 10, Sukoharjo',
                'kontak' => '(0271) 593-333',
                'website' => 'https://pn-sukoharjo.go.id',
                'logo' => 'instansi/PENGADILAN NEGERI.png',
                'facebook' => 'https://facebook.com/pn.sukoharjo',
                'instagram' => 'https://instagram.com/pn_sukoharjo',
                'twitter' => 'https://twitter.com/pnsukoharjo',
            ],
            [
                'nama' => 'Pengadilan Agama Kab. Sukoharjo',
                'subtitle' => 'PENGADILAN AGAMA SUKOHARJO',
                'alamat' => 'Jl. Ir. Soekarno No. 12, Sukoharjo',
                'kontak' => '(0271) 593-444',
                'website' => 'https://pa-sukoharjo.go.id',
                'logo' => 'instansi/PENGADILAN AGAMA.png',
                'facebook' => 'https://facebook.com/pa.sukoharjo',
                'instagram' => 'https://instagram.com/pa_sukoharjo',
                'twitter' => 'https://twitter.com/pasukoharjo',
            ],
            [
                'nama' => 'Kantor Pajak Pratama (KPP) Kab. Sukoharjo',
                'subtitle' => 'KPP SUKOHARJO',
                'alamat' => 'Jl. Slamet Riyadi No. 150, Sukoharjo',
                'kontak' => '(0271) 593-567',
                'website' => 'https://www.pajak.go.id',
                'logo' => 'instansi/KPP.png',
                'facebook' => 'https://facebook.com/pajaksukoharjo',
                'instagram' => 'https://instagram.com/pajaksukoharjo',
                'twitter' => 'https://twitter.com/pajaksukoharjo',
            ],
            [
                'nama' => 'Loka POM Surakarta',
                'subtitle' => 'LOKA POM SURAKARTA',
                'alamat' => 'Jl. Letjen Sutoyo No. 6, Surakarta',
                'kontak' => '(0271) 714-678',
                'website' => 'https://www.pom.go.id',
                'logo' => 'instansi/LOKA POM.png',
                'facebook' => 'https://facebook.com/lokapomsurakarta',
                'instagram' => 'https://instagram.com/bpom.surakarta',
                'twitter' => 'https://twitter.com/bpomsurakarta',
            ],
            [
                'nama' => 'PT Taspen',
                'subtitle' => 'PT. TASPEN',
                'alamat' => 'Jl. Slamet Riyadi No. 120, Surakarta',
                'kontak' => '(0271) 714-789',
                'website' => 'https://www.taspen.co.id',
                'logo' => 'instansi/TASPEN.png',
                'facebook' => 'https://facebook.com/taspen.kita',
                'instagram' => 'https://instagram.com/taspen.kita',
                'twitter' => 'https://twitter.com/taspen',
            ],
            [
                'nama' => 'BPJS Kesehatan',
                'subtitle' => 'BPJS KESEHATAN',
                'alamat' => 'Jl. Slamet Riyadi No. 210, Sukoharjo',
                'kontak' => '(0271) 593-678',
                'website' => 'https://www.bpjs-kesehatan.go.id',
                'logo' => 'instansi/BPJS KESEHATAN.png',
                'facebook' => 'https://facebook.com/BPJSKesehatanRI',
                'instagram' => 'https://instagram.com/bpjskesehatan_ri',
                'twitter' => 'https://twitter.com/BPJSKesehatanRI',
            ],
            [
                'nama' => 'BPJS Ketenagakerjaan',
                'subtitle' => 'BPJS KETENAGAKERJAAN',
                'alamat' => 'Jl. Slamet Riyadi No. 215, Sukoharjo',
                'kontak' => '(0271) 593-679',
                'website' => 'https://www.bpjsketenagakerjaan.go.id',
                'logo' => 'instansi/BPJS KETENAGAKERJAAN.png',
                'facebook' => 'https://facebook.com/BPJSTKinfo',
                'instagram' => 'https://instagram.com/bpjs.ketenagakerjaan',
                'twitter' => 'https://twitter.com/bpjstkinfo',
            ],
            [
                'nama' => 'Kantor Pertanahan Kab. Sukoharjo',
                'subtitle' => 'KANTOR PERTAHANAN',
                'alamat' => 'Jl. Ir. Soekarno No. 25, Sukoharjo',
                'kontak' => '(0271) 593-700',
                'website' => 'https://www.atrbpn.go.id',
                'logo' => 'instansi/KANTOR PERTAHANAN.png',
                'facebook' => 'https://facebook.com/KantahKabSukoharjo',
                'instagram' => 'https://instagram.com/kantahkabsukoharjo',
                'twitter' => 'https://twitter.com/KantahSkh',
            ],
            [
                'nama' => 'Dinas Kesehatan Kab. Sukoharjo',
                'subtitle' => 'DINKES SUKOHARJO',
                'alamat' => 'Jl. Raya Solo–Sukoharjo KM 5, Sukoharjo',
                'kontak' => '(0271) 593-555',
                'website' => 'https://dinkes.sukoharjokab.go.id',
                'logo' => 'instansi/DINAS KESEHATAN.png',
                'facebook' => 'https://facebook.com/dinkes.sukoharjo',
                'instagram' => 'https://instagram.com/dinkes_sukoharjo',
                'twitter' => 'https://twitter.com/dinkesskh',
            ],
            [
                'nama' => 'Dinas Perdagangan, Koperasi Usaha Kecil dan Menengah Kab. Sukoharjo',
                'subtitle' => 'DISKOPUMDAG SUKOHARJO',
                'alamat' => 'Jl. Veteran No. 15, Sukoharjo',
                'kontak' => '(0271) 593-601',
                'website' => 'https://disdagkopukm.sukoharjokab.go.id',
                'logo' => 'instansi/DINAS PERDAGANGAN.png',
                'facebook' => 'https://facebook.com/disdagkopukm.skh',
                'instagram' => 'https://instagram.com/disdagkopukmsukoharjo',
                'twitter' => 'https://twitter.com/disdagkopukmskh',
            ],
            [
                'nama' => 'Dinas Pekerjaan Umum dan Penataan Ruang Kab. Sukoharjo',
                'subtitle' => 'DPUPR SUKOHARJO',
                'alamat' => 'Jl. Ir. Soekarno No. 18, Sukoharjo',
                'kontak' => '(0271) 593-610',
                'website' => 'https://pupr.sukoharjokab.go.id',
                'logo' => 'instansi/DINAS PEKERJAAN UMUM.png',
                'facebook' => 'https://facebook.com/dpupr.sukoharjo',
                'instagram' => 'https://instagram.com/dpupr_sukoharjo',
                'twitter' => 'https://twitter.com/dpuprskh',
            ],
            [
                'nama' => 'Dinas Lingkungan Hidup Kab. Sukoharjo',
                'subtitle' => 'DLH SUKOHARJO',
                'alamat' => 'Jl. Jenderal Sudirman No. 22, Sukoharjo',
                'kontak' => '(0271) 593-620',
                'website' => 'https://dlh.sukoharjokab.go.id',
                'logo' => 'instansi/DINAS LINGKUNGAN HIDUP.png',
                'facebook' => 'https://facebook.com/dlh.sukoharjo',
                'instagram' => 'https://instagram.com/dlh_sukoharjo',
                'twitter' => 'https://twitter.com/dlhskh',
            ],
            [
                'nama' => 'Dinas Kependudukan dan Pencatatan Sipil Kab. Sukoharjo',
                'subtitle' => 'DISDUKCAPIL SUKOHARJO',
                'alamat' => 'Jl. Raya Sukoharjo–Solo KM 5, Sukoharjo',
                'kontak' => '(0271) 555-789',
                'website' => 'https://dukcapil.sukoharjokab.go.id',
                'logo' => 'instansi/DUKCAPIL.png',
                'facebook' => 'https://facebook.com/disdukcapil.sukoharjo',
                'instagram' => 'https://instagram.com/disdukcapilsukoharjo',
                'twitter' => 'https://twitter.com/capilskh',
            ],
            [
                'nama' => 'Badan Keuangan Daerah (BKD) Kab. Sukoharjo',
                'subtitle' => 'BKD SUKOHARJO',
                'alamat' => 'Jl. Jenderal Sudirman No. 30, Sukoharjo',
                'kontak' => '(0271) 593-630',
                'website' => 'https://bkd.sukoharjokab.go.id',
                'logo' => 'instansi/BKD.png',
                'facebook' => 'https://facebook.com/bkd.sukoharjo',
                'instagram' => 'https://instagram.com/bkd_sukoharjo',
                'twitter' => 'https://twitter.com/bkdskh',
            ],
            [
                'nama' => 'Dinas Sosial Kab. Sukoharjo',
                'subtitle' => 'DINSOS SUKOHARJO',
                'alamat' => 'Jl. Veteran No. 20, Sukoharjo',
                'kontak' => '(0271) 593-640',
                'website' => 'https://dinsos.sukoharjokab.go.id',
                'logo' => 'instansi/DINSOS.png',
                'facebook' => 'https://facebook.com/dinsos.sukoharjo',
                'instagram' => 'https://instagram.com/dinsos_sukoharjo',
                'twitter' => 'https://twitter.com/dinsosskh',
            ],
            [
                'nama' => 'Dinas Pendidikan dan Kebudayaan Kab. Sukoharjo',
                'subtitle' => 'DISDIK SUKOHARJO',
                'alamat' => 'Jl. Ir. Soekarno No. 35, Sukoharjo',
                'kontak' => '(0271) 593-650',
                'website' => 'https://disdikbud.sukoharjokab.go.id',
                'logo' => 'instansi/DINAS PENDIDIKAN.png',
                'facebook' => 'https://facebook.com/pdk.sukoharjo',
                'instagram' => 'https://instagram.com/disdikbud_sukoharjo',
                'twitter' => 'https://twitter.com/disdikskh',
            ],
            [
                'nama' => 'Badan Kesatuan Bangsa dan Politik',
                'subtitle' => 'KESBANGPOL',
                'alamat' => 'Jl. Jenderal Sudirman No. 40, Sukoharjo',
                'kontak' => '(0271) 593-660',
                'website' => 'https://kesbangpol.sukoharjokab.go.id',
                'logo' => 'instansi/BADAN KESATUAN BANGSA DAN POLITIK.png',
                'facebook' => 'https://facebook.com/kesbangpol.sukoharjo',
                'instagram' => 'https://instagram.com/kesbangpolsukoharjo',
                'twitter' => 'https://twitter.com/kesbangskh',
            ],
            [
                'nama' => 'Dinas Kearsipan dan Perpustakaan Kab. Sukoharjo',
                'subtitle' => 'DISPUSIP SUKOHARJO',
                'alamat' => 'Jl. Slamet Riyadi No. 300, Sukoharjo',
                'kontak' => '(0271) 593-670',
                'website' => 'https://dispussip.sukoharjokab.go.id',
                'logo' => 'instansi/DISPUSIP.png',
                'facebook' => 'https://facebook.com/perpustakaan.sukoharjo',
                'instagram' => 'https://instagram.com/dispusip_sukoharjo',
                'twitter' => 'https://twitter.com/dispusipskh',
            ],
            [
                'nama' => 'Dinas Perhubungan Kab. Sukoharjo',
                'subtitle' => 'DISHUB SUKOHARJO',
                'alamat' => 'Jl. Ir. Soekarno No. 45, Sukoharjo',
                'kontak' => '(0271) 593-680',
                'website' => 'https://dishub.sukoharjokab.go.id',
                'logo' => 'instansi/DISHUB.png',
                'facebook' => 'https://facebook.com/dishub.sukoharjo',
                'instagram' => 'https://instagram.com/dishub_sukoharjo',
                'twitter' => 'https://twitter.com/dishubskh',
            ],
            [
                'nama' => 'Dinas Perindustrian dan Tenaga Kerja Kab. Sukoharjo',
                'subtitle' => 'DISPERMAKER SUKOHARJO',
                'alamat' => 'Jl. Veteran No. 25, Sukoharjo',
                'kontak' => '(0271) 593-690',
                'website' => 'https://disperinaker.sukoharjokab.go.id',
                'logo' => 'instansi/DISPERMAKER.png',
                'facebook' => 'https://facebook.com/disperinaker.sukoharjo',
                'instagram' => 'https://instagram.com/disperinaker_sukoharjo',
                'twitter' => 'https://twitter.com/disperinakerskh',
            ],
            [
                'nama' => 'DPPKBP3A Kab. Sukoharjo',
                'subtitle' => 'DPPKBP3A SUKOHARJO',
                'alamat' => 'Jl. Jenderal Sudirman No. 50, Sukoharjo',
                'kontak' => '(0271) 593-701',
                'website' => 'https://dppkbp3a.sukoharjokab.go.id',
                'logo' => 'instansi/DPPKBP3A.png',
                'facebook' => 'https://facebook.com/dppkbp3a.sukoharjo',
                'instagram' => 'https://instagram.com/dppkbp3a_sukoharjo',
                'twitter' => 'https://twitter.com/dppkbp3askh',
            ],
            [
                'nama' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu (DPMPTSP) Kab. Sukoharjo',
                'subtitle' => 'DPMPTSP SUKOHARJO',
                'alamat' => 'Jl. Raya Sukoharjo–Solo KM 6, Sukoharjo',
                'kontak' => '(0271) 593-710',
                'website' => 'https://dpmptsp.sukoharjokab.go.id',
                'logo' => 'instansi/DPMPTSP SUKOHARJO.png',
                'facebook' => 'https://facebook.com/dpmptsp.sukoharjo',
                'instagram' => 'https://instagram.com/dpmptsp_sukoharjo',
                'twitter' => 'https://twitter.com/dpmptspskh',
            ],
            [
                'nama' => 'Bank Jateng Cabang Sukoharjo',
                'subtitle' => 'BANK JATENG',
                'alamat' => 'Jl. Slamet Riyadi No. 88, Sukoharjo',
                'kontak' => '(0271) 593-720',
                'website' => 'https://www.bankjateng.co.id',
                'logo' => 'instansi/BANK JATENG.png',
                'facebook' => 'https://facebook.com/bankjateng.official',
                'instagram' => 'https://instagram.com/bankjateng',
                'twitter' => 'https://twitter.com/bank_jateng',
            ],
            [
                'nama' => 'BRI',
                'subtitle' => 'BANK BRI',
                'alamat' => 'Jl. Slamet Riyadi No. 90, Sukoharjo',
                'kontak' => '1500017',
                'website' => 'https://bri.co.id',
                'logo' => 'instansi/BRI.png',
                'facebook' => 'https://facebook.com/BRIofficialpage',
                'instagram' => 'https://instagram.com/bankbri_id',
                'twitter' => 'https://twitter.com/promo_BRI',
            ],
            [
                'nama' => 'Bank Sukoharjo',
                'subtitle' => 'BANK SUKOHARJO',
                'alamat' => 'Jl. Jenderal Sudirman No. 60, Sukoharjo',
                'kontak' => '(0271) 593-740',
                'website' => 'https://www.banksukoharjo.co.id',
                'logo' => 'instansi/BANK SUKOHARJO.png',
                'facebook' => 'https://facebook.com/BankSukoharjo',
                'instagram' => 'https://instagram.com/bank_sukoharjo',
                'twitter' => 'https://twitter.com/banksukoharjo',
            ],
            [
                'nama' => 'PDAM Tirta Makmur',
                'subtitle' => 'PDAM TIRTA MAKMUR',
                'alamat' => 'Jl. Ir. Soekarno No. 55, Sukoharjo',
                'kontak' => '(0271) 593-750',
                'website' => 'https://pdam.sukoharjokab.go.id',
                'logo' => 'instansi/TIRTA.png',
                'facebook' => 'https://facebook.com/pdam.sukoharjo',
                'instagram' => 'https://instagram.com/pdam_sukoharjo',
                'twitter' => 'https://twitter.com/pdamsukoharjo',
            ],
            [
                'nama' => 'PT. Pegadaian',
                'subtitle' => 'PT. PEGADAIAN',
                'alamat' => 'Jl. Slamet Riyadi No. 95, Sukoharjo',
                'kontak' => '(0271) 593-760',
                'website' => 'https://www.pegadaian.co.id',
                'logo' => 'instansi/PEGADAIAN.png',
                'facebook' => 'https://facebook.com/PegadaianPersero',
                'instagram' => 'https://instagram.com/pegadaian_id',
                'twitter' => 'https://twitter.com/pegadaian',
            ],
        ];

        // 5. Loop untuk insert data ke Database
        foreach ($instansis as $data) {
            Instansi::create([
                'nama_instansi'   => $data['nama'],
                'subtitle'        => $data['subtitle'],
                'alamat'          => $data['alamat'],
                'kontak'          => $data['kontak'],
                'website'         => $data['website'],
                'facebook'        => $data['facebook'],
                'instagram'       => $data['instagram'],
                'twitter'         => $data['twitter'],
                'logo_url'        => $data['logo'],
                
                // Email: Membuat email dummy otomatis berdasarkan slug jika data asli tidak ada
                'email'           => 'info@' . Str::slug($data['subtitle']) . '.go.id',
                
                // Slug: Untuk URL yang SEO Friendly
                'slug'            => Str::slug($data['nama']),

                // Placeholder untuk Unggah Foto Gerai & File Mekanisme (Bisa dikosongkan/null)
                'foto_gerai'      => 'instansi/gerai bank bri.png', 
                'file_mekanisme'  => 'instansi/Mekanisme Bri.pdf',
            ]);
        }
    }
}